BRANCH_NAME: v0_3
DIR_FILE_FTL: /home/runner/work/WebAppTesi/WebAppTesi/WebAppHooks/catalogoProdottiBoot/src/main/resources/templates/indexProdottiOriginaleNoHooks.ftl
FILE_POM_MAIN_PROJECT: /home/runner/work/WebAppTesi/WebAppTesi/WebAppHooks/catalogoProdottiBoot/pom.xml
DIR_POM_MAIN_PROJECT: /home/runner/work/WebAppTesi/WebAppTesi/WebAppHooks/catalogoProdottiBoot
DIR_JAR_MAIN_PROJECT: /home/runner/work/WebAppTesi/WebAppTesi/WebAppHooks/catalogoProdottiBoot/target
TEST_TO_EXECUTE: testSuiteHooks_release_1_0,testSuiteHooks2_release_1_0,testSuiteHooks3_release_1_0
DIR_SUREFIRE_REPORTS: /home/runner/work/WebAppTesi/WebAppTesi/WebAppHooks/catalogoProdottiBoot/target/surefire-reports
DIR_TEST_SUITE: /home/runner/work/WebAppTesi/WebAppTesi/TestSuite
NOME_TEST_SUITE: TestSuite
DIR_TEST_SUITE_HOOKS: /home/runner/work/WebAppTesi/WebAppTesi/TestSuite/TestSuiteHooks
NOME_TEST_SUITE_HOOKS: TestSuiteHooks
DIR_TEST_SUITE_HOOKS_STORICO: /home/runner/work/WebAppTesi/WebAppTesi/TestSuite/TestSuiteHooks/StoricoTest
NOME_TEST_SUITE_HOOKS_STORICO: StoricoTest
INFO_COMMIT_TEST_SUITE: Test Suite Hooks Prova2 con Environment Variable
REPORT_DIRECTORYNAME_WITH_PROJECT_VERSION: report_test_v1_1
GITHUB_EMAIL: talitrogian2@gmail.com
GITHUB_NAME: gianlucat97
GITHUB_PASSWORD: Sharingan268
NOME_REPORT_FINALE: tabellaReportTest
