# This is a basic workflow to help you get started with Actions

name: Github Actions Maven Build Example 2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ v0_3 ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Step 2 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

             
      - name: Step 4 - List the current directory
        run: |
          ls -a
          echo 'Hello, world. Commit 2 prova' >provaHello.txt
          ls -a 
          echo "Vediamo il contenuto del file provaHello.txt"
          cat provaHello.txt
          
          
      - name: Step 5 - Prova Add file to github
        run: |
          ls -a
          git status
          git config --global user.email "talitrogian2@gmail.com"
          git config --global user.name "gianlucat97"
          git config --global user.password "Sharingan268"
          git add provaHello.txt
          git commit -m "Prova 3 aggiunta file txt da container"
          git branch -M v0_3
          git push -u origin v0_3
