# This is a basic workflow to help you get started with Actions

name: Github Actions Maven Build Example

# Controls when the workflow will run
on:
  release:
    types: [published]


 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: envForGithubActions
    
      
   # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Step 2 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Step 2.2 - Visualizzare tag corrente
        run: |
          echo "Vediamo il contenuto iniziale di provaHello.txt"
          cat provaHello.txt
          sudo bash -c 'echo "Ciaoooooooooo22222222" > provaHello.txt'
          echo "Vediamo il contenuto finale di provaHello.txt"
          cat provaHello.txt
          echo "Visualizziamo il tag name:"
          echo "${GITHUB_REF#refs/tags/}"
          
      - name: Step 3 - Push dei cambiamenti release
        run: |
          git config --global user.email "${{ secrets.EMAIL_ACCOUNT_GITHUB }}"
          git config --global user.name "${{ secrets.NOME_ACCOUNT_GITHUB }}"
          git config --global user.password "${{ secrets.PASSWORD_ACCOUNT_GITHUB }}"
          echo "Andiamo ad aggiungere la cartella dei report"
          git add provaHello.txt
          echo "Cartella aggiunta!"
          git commit -m "${{ secrets.INFO_COMMIT_TEST_SUITE }}"
          echo "Commit effettuato"
          git push -u origin ${GITHUB_REF#refs/tags/}
          echo "Push effettuato"
          
          
          
          
